#!/usr/bin/python3
"""

This is a setup script for the Ubuntu Old-Fashioned image builder. Its
purpose is to make the process of setting up a new build environment
(e.g. a VPS) more hands-free.

Note that any "extra" build hooks must still be manually copied into the
appropriate hooks directory.

"""
import os

from subprocess import call

import platform
from typing import Dict, List, Text, Tuple  # noqa

PKG_INSTALL_CMDS = [
    ["sudo", "add-apt-repository", "-y", "ppa:cloud-images/old-fashioned"],
    ["sudo", "add-apt-repository", "-y", "ppa:launchpad/ppa"],
    ["sudo", "apt-get", "update"],
    ["sudo", "apt-get", "install", "-y", "python-distro-info"],
    ["sudo", "apt-get", "install", "-y", "oldfashioned"],
    ["sudo", "apt-get", "install", "-y", "launchpad-buildd", "bzr",
     "python-ubuntutools",
     ],
]

LIVECD_ROOTFS_GIT = "https://git.launchpad.net/livecd-rootfs"


def input_repo():
    # type: () -> List[Text]
    vcs = {
            '1': "git",
            '2': "bzr",
            }

    def print_opts(ks):
        # type: (List[Text]) -> None
        for key in ks:
            print("{}: {}".format(key, vcs[key]))

    print("Which VCS?")
    ks = sorted(list(vcs.keys()), key=lambda x: int(x))
    print_opts(ks)

    choice = ""
    while choice not in ks:
        choice = input("> ")
        if choice not in ks:
            print("Please choose from the options listed.")
            print_opts(ks)

    cmd = [vcs[choice]]
    if choice == '1':
        cmd += ["clone"]
    else:
        cmd += ["branch"]

    print("Please enter the repo you would like to clone:")
    repo = input("> ")

    correct = False
    done = "n"
    while not correct:
        print(repo)
        print("Is the above correct? [y/n]")
        done = input("> ")
        if done.lower()[0] == 'y':
            break
        else:
            print("Please enter the repo you would like to clone:")
            repo = input("> ")

    cmd += repo.split(' ')

    return cmd


if __name__ == '__main__':
    if '16.04' not in platform.linux_distribution():
        print("Old-fashioned must be run on Xenial Ubuntu.")
        exit(1)

    def print_sorted(d):
        ordered = sorted(list(d.keys()), key=lambda x: int(x))
        for key in ordered:
            print("{}: {}".format(key, d.get(key)))

    for cmd in PKG_INSTALL_CMDS:
        call(cmd)

    from distro_info import UbuntuDistroInfo

    supported_suites = UbuntuDistroInfo.supported()
    extra_options = ['master', 'package', 'custom', 'none']
    user_options = supported_suites + extra_options
    user_options -= UbuntuDistroInfo.devel()
    LIVECD_ROOTFS_OPTIONS = {i: opt for i, opt in enumerate(user_options)}

    print()
    print("Choose livecd-rootfs branch/option")
    print_sorted(LIVECD_ROOTFS_OPTIONS)

    ks = LIVECD_ROOTFS_OPTIONS.keys()
    choice = ""
    while choice not in ks:
        choice = input("> ")
        if choice not in ks:
            print("Please choose from the options listed.")
            print_sorted(LIVECD_ROOTFS_OPTIONS)

    selection = LIVECD_ROOTFS_OPTIONS[int(choice)]

    if selection not in extra_options:
        cmd = ["git", "clone", "-b",
               'ubuntu/{}'.format(LIVECD_ROOTFS_OPTIONS[choice]),
               LIVECD_ROOTFS_GIT]
    elif selection == 'package':
        cmd = ["sudo", "apt-get", "install", "-y", "livecd-rootfs"]
    elif selection == 'custom':
        cmd = input_repo()
    else:
        print("'none' option selected. Skipping livecd-rootfs install...")

    repo_dir = "/livecd-rootfs"
    parent_dir = os.path.abspath(os.path.join("./", os.pardir))
    cmd += [parent_dir + repo_dir]
    print("Executing {}".format(' '.join(cmd)))
    call(cmd)

    print("Done installing tools. All that's left to do is clone and copy any "
          "additional hooks you might want to run.")
    print("Run old-fashioned via:")
    print("    cd <livecd-rootfs repo>")
    print("    sudo -E old-fashioned-image-build --series <series>")
